# -*- coding: utf-8 -*-

---
channels: 3
classes: 10
trials: 5
epochs: 100
batch_size: 200
learning_rate: 0.01
train_autoencoder: True
autoencoder_epochs: 50
autoencoder_learning_rate: 0.0001
save_folder_name: "results"
...